# .readthedocs.yaml
version: 2

# Define which Python version to use
python:
  version: 3.11
  install:
    - requirements: source/requirements.txt

# Build configuration
sphinx:
  configuration: source/conf.py

# Optionally, define which branches to build
build:
  image: latest
  # optional: build only specific branches
  # only:
  #   - main
  #   - develop

# Optionally, define subprojects (for multi-version docs)
# subprojects:
#   myproject: https://myproject.readthedocs.io/
