import { NextResponse } from "next/server";

const genres = [
    { id: "Comedy", slug: "comedy" },
    { id: "Supernatural", slug: "supernatural" },
    { id: "Drama", slug: "drama" },
    { id: "Fantasy", slug: "fantasy" },
    { id: "Action", slug: "action" },
    { id: "Josei", slug: "josei" },
    { id: "Adventure", slug: "adventure" },
    { id: "Romance", slug: "romance" },
    { id: "Smut", slug: "smut" },
    { id: "Manhwa", slug: "manhwa" },
    { id: "Tragedy", slug: "tragedy" },
    { id: "Slice of life", slug: "slice-of-life" },
    { id: "School life", slug: "school-life" },
    { id: "Seinen", slug: "seinen" },
    { id: "Historical", slug: "historical" },
    { id: "Harem", slug: "harem" },
    { id: "Horror", slug: "horror" },
    { id: "Psychological", slug: "psychological" },
    { id: "Mystery", slug: "mystery" },
    { id: "Shounen", slug: "shounen" },
    { id: "Martial arts", slug: "martial-arts" },
    { id: "Manhua", slug: "manhua" },
    { id: "Shoujo", slug: "shoujo" },
    { id: "Isekai", slug: "isekai" },
    { id: "Erotica", slug: "erotica" },
    { id: "Gender bender", slug: "gender-bender" },
    { id: "Mature", slug: "mature" },
    { id: "Webtoons", slug: "webtoons" },
    { id: "Shoujo ai", slug: "shoujo-ai" },
    { id: "Yaoi", slug: "yaoi" },
    { id: "Yuri", slug: "yuri" },
    { id: "Medical", slug: "medical" },
    { id: "Mecha", slug: "mecha" },
    { id: "Shounen ai", slug: "shounen-ai" },
    { id: "Sports", slug: "sports" },
    { id: "Cooking", slug: "cooking" },
    { id: "Sci fi", slug: "sci-fi" },
    { id: "One shot", slug: "one-shot" },
    { id: "Ecchi", slug: "ecchi" },
    { id: "Adult", slug: "adult" },
    { id: "Pornographic", slug: "pornographic" },
    { id: "Doujinshi", slug: "doujinshi" },
    { id: "Long Strip", slug: "long-strip" },
    { id: "Survival", slug: "survival" },
    { id: "Adaptation", slug: "adaptation" },
    { id: "Official Colored", slug: "official-colored" },
    { id: "Wuxia", slug: "wuxia" },
    { id: "Thriller", slug: "thriller" },
    { id: "Web Comic", slug: "web-comic" },
    { id: "Full Color", slug: "full-color" },
    { id: "Reincarnation", slug: "reincarnation" },
    { id: "Monsters", slug: "monsters" },
    { id: "Military", slug: "military" },
    { id: "Philosophical", slug: "philosophical" },
    { id: "Gyaru", slug: "gyaru" },
    { id: "Bloody", slug: "bloody" },
    { id: "Demons", slug: "demons" },
    { id: "System", slug: "system" },
    { id: "Loli", slug: "loli" },
    { id: "Ninja", slug: "ninja" },
    { id: "Incest", slug: "incest" },
    { id: "Crime", slug: "crime" },
    { id: "Office Workers", slug: "office-workers" },
    { id: "Sexual Violence", slug: "sexual-violence" },
    { id: "Crossdressing", slug: "crossdressing" },
    { id: "Gore", slug: "gore" },
    { id: "Delinquents", slug: "delinquents" },
    { id: "Shota", slug: "shota" },
    { id: "Police", slug: "police" },
    { id: "Manga", slug: "manga" },
    { id: "Time Travel", slug: "time-travel" },
    { id: "Monster Girls", slug: "monster-girls" },
    { id: "Anthology", slug: "anthology" },
    { id: "4-Koma", slug: "4-koma" },
    { id: "Oneshot", slug: "oneshot" },
    { id: "Animals", slug: "animals" },
    { id: "Heartwarming", slug: "heartwarming" },
    { id: "Superhero", slug: "superhero" },
    { id: "Magic", slug: "magic" },
    { id: "Genderswap", slug: "genderswap" },
    { id: "Post-Apocalyptic", slug: "post-apocalyptic" },
    { id: "Music", slug: "music" },
    { id: "Self-Published", slug: "self-published" },
    { id: "Aliens", slug: "aliens" },
    { id: "Villainess", slug: "villainess" },
    { id: "Virtual Reality", slug: "virtual-reality" },
    { id: "Ghosts", slug: "ghosts" },
    { id: "Award Winning", slug: "award-winning" },
    { id: "Video Games", slug: "video-games" },
    { id: "Magical Girls", slug: "magical-girls" },
    { id: "Reverse Harem", slug: "reverse-harem" },
    { id: "Fan Colored", slug: "fan-colored" },
    { id: "Zombies", slug: "zombies" },
    { id: "Mafia", slug: "mafia" },
    { id: "Webtoon", slug: "webtoon" },
    { id: "Royal family", slug: "royal-family" },
    { id: "Manhwa Hot", slug: "manhwa-hot" },
    { id: "Traditional Games", slug: "traditional-games" },
    { id: "Magical", slug: "magical" },
    { id: "Vampires", slug: "vampires" },
    { id: "Revenge", slug: "revenge" },
    { id: "ecchi 2", slug: "ecchi-2" },
    { id: "Samurai", slug: "samurai" },
    { id: "Yaoi(BL)", slug: "yaoi-bl" },
    { id: "Monster", slug: "monster" },
    { id: "Super Power", slug: "super-power" },
    { id: "Animal", slug: "animal" },
    { id: "Game", slug: "game" },
    { id: "Comic", slug: "comic" },
    { id: "Science fiction", slug: "science-fiction" },
    { id: "Office", slug: "office" },
    { id: "School", slug: "school" },
    { id: "Parody", slug: "parody" },
    { id: "Iyashikei", slug: "iyashikei" },
    { id: "Girls Love", slug: "girls-love" },
    { id: "Boys Love", slug: "boys-love" },
    { id: "Mahou Shoujo", slug: "mahou-shoujo" },
    { id: "Suspense", slug: "suspense" },
    { id: "Vampire", slug: "vampire" },
    { id: "Kids", slug: "kids" },
    { id: "Space", slug: "space" },
    { id: "Gourmet", slug: "gourmet" },
    { id: "Soft Yaoi", slug: "soft-yaoi" },
    { id: "Avant Garde", slug: "avant-garde" },
    { id: "cartoon", slug: "cartoon" },
    { id: "violence", slug: "violence" },
    { id: "imageset", slug: "imageset" },
    { id: "teacher_student", slug: "teacher-student" },
    { id: "cultivation", slug: "cultivation" },
    { id: "death_game", slug: "death-game" },
    { id: "degeneratemc", slug: "degeneratemc" },
    { id: "cars", slug: "cars" },
    { id: "showbiz", slug: "showbiz" },
    { id: "blackmail", slug: "blackmail" },
    { id: "western", slug: "western" },
    { id: "xianxia", slug: "xianxia" },
    { id: "fetish", slug: "fetish" },
    { id: "netorare", slug: "netorare" },
    { id: "age_gap", slug: "age-gap" },
    { id: "ai_art", slug: "ai-art" },
    { id: "master_servant", slug: "master-servant" },
    { id: "college_life", slug: "college-life" },
    { id: "childhood_friends", slug: "childhood-friends" },
    { id: "non_human", slug: "non-human" },
    { id: "dementia", slug: "dementia" },
    { id: "Informative", slug: "informative" },
    { id: "Graphic Novel", slug: "graphic-novel" },
    { id: "Royalty", slug: "royalty" },
    { id: "Liexing", slug: "liexing" },
    { id: "Ping Ping Jun", slug: "ping-ping-jun" },
    { id: "Josei(W)", slug: "josei-w" },
    { id: "Shoujo(G)", slug: "shoujo-g" },
    { id: "User Created", slug: "user-created" },
    { id: "2019", slug: "2019" },
    { id: "BL", slug: "bl" },
    { id: "Reverse", slug: "reverse" },
    { id: "artbook", slug: "artbook" },
    { id: "omegaverse", slug: "omegaverse" },
    { id: "cheating_infidelity", slug: "cheating-infidelity" },
    { id: "sm_bdsm", slug: "sm-bdsm" },
    { id: "bodyswap", slug: "bodyswap" },
    { id: "netori", slug: "netori" },
    { id: "old_people", slug: "old-people" },
    { id: "beasts", slug: "beasts" },
    { id: "Seinen(M)", slug: "seinen-m" },
    { id: "Shounen(B)", slug: "shounen-b" },
    { id: "Creators", slug: "creators" },
    { id: "Others", slug: "others" },
    { id: "step_family", slug: "step-family" },
    { id: "brocon_siscon", slug: "brocon-siscon" },
    { id: "Korean", slug: "korean" }
];

export async function GET() {
	const genreList = genres.map((g) => ({
		id: g.id,
		slug: g.slug,
	}));

	return NextResponse.json(genreList);
}